# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_chinaarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chinaarea',
            old_name='price',
            new_name='value',
        ),
    ]
