# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171128_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaAreaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ChinaArea',
        ),
    ]
