# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_dsahboard_ordercount_predict_productcount_typecount_worldareadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercount',
            old_name='date',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='predict',
            old_name='date',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='productcount',
            old_name='date',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='typecount',
            old_name='date',
            new_name='time',
        ),
    ]
