# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20171207_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercount',
            old_name='time',
            new_name='riqi',
        ),
    ]
