# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20171207_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderCount',
            new_name='OrderCountOne',
        ),
    ]
