# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20171207_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=64)),
                ('order_count', models.IntegerField()),
                ('product_count', models.IntegerField()),
                ('allprice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='OrderCountOne',
        ),
        migrations.RenameField(
            model_name='predict',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='productcount',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='typecount',
            old_name='time',
            new_name='date',
        ),
    ]
