# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20171208_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcount',
            name='hufu_Schaebens',
        ),
    ]
