# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_productcount_hufu_schaebens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='hufu_Schaebens',
        ),
    ]
