# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_predict_hufu_schaebens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dsahboard',
            new_name='Dashboard',
        ),
    ]
